### ISSUE TITLE
1.19.4挂了好像

### ISSUE THREAD

**Issue by XiaoJiang0208** [LSDogX/CustomSprays#1]
paper1.19.4无法喷漆

 Thread Craft Scheduler Thread - 10 - CustomSprays failed main thread check: Cannot remove entity off-main
java.lang.Throwable: null
        at io.papermc.paper.util.TickThread.ensureTickThread(TickThread.java:50) ~[paper-1.19.4.jar:git-Paper-525]
        at net.minecraft.world.entity.Entity.setRemoved(Entity.java:4530) ~[paper-1.19.4.jar:git-Paper-525]
        at net.minecraft.world.entity.Entity.remove(Entity.java:678) ~[paper-1.19.4.jar:git-Paper-525]
        at net.minecraft.world.entity.Entity.kill(Entity.java:655) ~[paper-1.19.4.jar:git-Paper-525]
        at net.minecraft.world.entity.decoration.ItemFrame.kill(ItemFrame.java:178) ~[?:?]
        at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:578) ~[?:?]
        at fun.LSDog.CustomSprays.utils.NMS.getMcEntityId(NMS.java:238) ~[CustomSprays.jar:?]
        at fun.LSDog.CustomSprays.spray.SprayBase.spawn(SprayBase.java:134) ~[CustomSprays.jar:?]
        at fun.LSDog.CustomSprays.spray.SprayBase.create(SprayBase.java:108) ~[CustomSprays.jar:?]
        at fun.LSDog.CustomSprays.spray.SprayManager.spray(SprayManager.java:61) ~[CustomSprays.jar:?]
        at fun.LSDog.CustomSprays.Events.lambda$null$0(Events.java:42) ~[CustomSprays.jar:?]
        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.4.jar:git-Paper-525]
        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.19.4.jar:git-Paper-525]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.19.4.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.lang.Thread.run(Thread.java:1589) ~[?:?]
[11:00:49 WARN]: java.lang.reflect.InvocationTargetException
[11:00:49 WARN]:        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:119)
[11:00:49 WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:578)
[11:00:49 WARN]:        at CustomSprays.jar//fun.LSDog.CustomSprays.utils.NMS.getMcEntityId(NMS.java:238)
[11:00:49 WARN]:        at CustomSprays.jar//fun.LSDog.CustomSprays.spray.SprayBase.spawn(SprayBase.java:134)
[11:00:49 WARN]:        at CustomSprays.jar//fun.LSDog.CustomSprays.spray.SprayBase.create(SprayBase.java:108)
[11:00:49 WARN]:        at CustomSprays.jar//fun.LSDog.CustomSprays.spray.SprayManager.spray(SprayManager.java:61)
[11:00:49 WARN]:        at CustomSprays.jar//fun.LSDog.CustomSprays.Events.lambda$null$0(Events.java:42)
[11:00:49 WARN]:        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101)
[11:00:49 WARN]:        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[11:00:49 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[11:00:49 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[11:00:49 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[11:00:49 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1589)
[11:00:49 WARN]: Caused by: java.lang.IllegalStateException: Cannot remove entity off-main
[11:00:49 WARN]:        at io.papermc.paper.util.TickThread.ensureTickThread(TickThread.java:51)
[11:00:49 WARN]:        at net.minecraft.world.entity.Entity.b(Entity.java:4530)
[11:00:49 WARN]:        at net.minecraft.world.entity.Entity.a(Entity.java:678)
[11:00:49 WARN]:        at net.minecraft.world.entity.Entity.ah(Entity.java:655)
[11:00:49 WARN]:        at net.minecraft.world.entity.decoration.EntityItemFrame.ah(EntityItemFrame.java:178)
[11:00:49 WARN]:        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
[11:00:49 WARN]:        ... 12 more

**Comment by LSDogX** [comment]
收到 下周末 **(5.13~5.14)** 修复
会附加新功能

**Comment by XiaoJiang0208** [comment]
wow，期待୧((〃•̀ꇴ•〃))૭⁺✧，大佬加油

**Comment by LSDogX** [comment]
解决！！

**Comment by XiaoJiang0208** [comment]
太棒哩😁🥰
