### ISSUE TITLE
触发Region检测之类的导致无法喷漆?）

### ISSUE THREAD

**Issue by SakuranaRanbom** [LSDogX/CustomSprays#2]
无op权限时候在任何地方都无法喷漆（已经给予了config.yml中的权限）

purpur 1.19.4

有worldguard和griefdefender

``` [22:37:09 WARN]: java.lang.IllegalArgumentException: java.lang.ClassCastException@56eece15
[22:37:09 WARN]:        at jdk.internal.reflect.GeneratedMethodAccessor145.invoke(Unknown Source)
[22:37:09 WARN]:        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[22:37:09 WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[22:37:09 WARN]:        at CustomSprays1.jar//fun.LSDog.CustomSprays.utils.RegionChecker.getRegionNames(RegionChecker.java:143)
[22:37:09 WARN]:        at CustomSprays1.jar//fun.LSDog.CustomSprays.utils.RegionChecker.isLocInDisabledRegion(RegionChecker.java:88)
[22:37:09 WARN]:        at CustomSprays1.jar//fun.LSDog.CustomSprays.spray.SprayBase.create(SprayBase.java:93)
[22:37:09 WARN]:        at CustomSprays1.jar//fun.LSDog.CustomSprays.spray.SprayManager.spray(SprayManager.java:63)
[22:37:09 WARN]:        at CustomSprays1.jar//fun.LSDog.CustomSprays.Events.lambda$null$0(Events.java:54)
[22:37:09 WARN]:        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101)
[22:37:09 WARN]:        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[22:37:09 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[22:37:09 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[22:37:09 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[22:37:09 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)```

**Comment by SakuranaRanbom** [comment]
griefdefender-bukkit-2.3.8.jar   worldguard-bukkit-7.0.8-dist.jar
好像确实只有这一部分报错。
```[22:48:32 INFO]: Leo_Ranbom issued server command: /deop Leo_Ranbom
[22:48:32 INFO]: [Leo_Ranbom: Made Leo_Ranbom no longer a server operator]
[22:49:14 WARN]: java.lang.IllegalArgumentException: java.lang.ClassCastException@36a960ba
[22:49:14 WARN]:        at jdk.internal.reflect.GeneratedMethodAccessor145.invoke(Unknown Source)
[22:49:14 WARN]:        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[22:49:14 WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[22:49:14 WARN]:        at CustomSprays1.jar//fun.LSDog.CustomSprays.utils.RegionChecker.getRegionNames(RegionChecker.java:143)
[22:49:14 WARN]:        at CustomSprays1.jar//fun.LSDog.CustomSprays.utils.RegionChecker.isLocInDisabledRegion(RegionChecker.java:88)
[22:49:14 WARN]:        at CustomSprays1.jar//fun.LSDog.CustomSprays.spray.SprayBase.create(SprayBase.java:93)
[22:49:14 WARN]:        at CustomSprays1.jar//fun.LSDog.CustomSprays.spray.SprayManager.spray(SprayManager.java:63)
[22:49:14 WARN]:        at CustomSprays1.jar//fun.LSDog.CustomSprays.Events.lambda$null$0(Events.java:54)
[22:49:14 WARN]:        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101)
[22:49:14 WARN]:        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[22:49:14 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[22:49:14 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[22:49:14 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[22:49:14 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
> 
```
上面是deop指令的反馈，下面是命令输入框。

**Comment by LSDogX** [comment]
ok 我觉得我犯了一个很蠢的错误，不介意的话请试下这个重新构建的，看看现在可不可以用了（**先解压出.jar再放plaugins里**），如果还是不行我再自己搭个端实验一下
👇
[CustomSprays_from_1.5.8_fix_GriefDefender.zip](https://github.com/LSDogX/CustomSprays/files/11969660/CustomSprays_from_1.5.8_fix_GriefDefender.zip)

**Comment by SakuranaRanbom** [comment]
> ok 我觉得我犯了一个很蠢的错误，不介意的话请试下这个重新构建的，看看现在可不可以用了（**先解压出.jar再放plugins里**），如果还是不行我再自己搭个端实验一下 👇 [CustomSprays_from_1.5.8_fix_GriefDefender.zip](https://github.com/LSDogX/CustomSprays/files/11969660/CustomSprays_from_1.5.8_fix_GriefDefender.zip)

已经可以用了(感谢orz

**Comment by LSDogX** [comment]
👌
