### ISSUE TITLE
1.20.2 Unable to spray paint.

### ISSUE THREAD

**Issue by Eris7090** [LSDogX/CustomSprays#8]
```
[20:06:55 WARN]: java.lang.ClassCastException: class net.minecraft.network.protocol.game.VecDeltaCodec cannot be cast to class java.lang.Integer (net.minecraft.network.protocol.game.VecDeltaCodec is in unnamed module of loader java.net.URLClassLoader @4ee285c6; java.lang.Integer is in module java.base of loader 'bootstrap')
[20:06:55 WARN]:        at CustomSprays.jar//fun.LSDog.CustomSprays.utils.NMS.getMcEntityId(NMS.java:257)
[20:06:55 WARN]:        at CustomSprays.jar//fun.LSDog.CustomSprays.spray.SprayBig.spawn(SprayBig.java:96)
[20:06:55 WARN]:        at CustomSprays.jar//fun.LSDog.CustomSprays.spray.SprayBase.create(SprayBase.java:109)
[20:06:55 WARN]:        at CustomSprays.jar//fun.LSDog.CustomSprays.spray.SprayManager.spray(SprayManager.java:88)
[20:06:55 WARN]:        at CustomSprays.jar//fun.LSDog.CustomSprays.Events.lambda$null$1(Events.java:56)
[20:06:55 WARN]:        at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftTask.run(CraftTask.java:101)
[20:06:55 WARN]:        at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[20:06:55 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[20:06:55 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[20:06:55 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[20:06:55 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1589)
```

**Information (please complete the following information):**
 - 1.20.2
 - purpur
 - 1.20.2
 - 1.5.8

**Comment by LSDogX** [comment]
got that, will test it later

**Comment by LSDogX** [comment]
Fixed!
*with a gift 1.7.10 (anyone using this?)*

**Comment by Eris7090** [comment]
Thank you!
